
DELETE FROM THING;
DELETE FROM HOMEADDRESS;
DELETE FROM PURCHASEPART;
DELETE FROM PURCHASE;
DELETE FROM Client;
INSERT INTO Thing(THING_ID,THING_NAME,THING_DESCRIPTION,Thing.THING_SIZE,thing.PURCHASE_PRICE,thing.SELL_PRICE)
VALUES (1, 'Kaffeemaschine', 'Moderne Filterkaffeemaschine',5, 45.00, 69.99);
commit;

INSERT INTO CLIENT(client_id,name,CLIENT.EMAIL_ADDRESS)
VALUES (1, 'Anna Muster', 'anna.muster@example.com');

INSERT INTO HOMEADDRESS(HOMEADDRESS.HOME_ADDRESS_ID,HOMEADDRESS.CLIENT_ID,HOMEADDRESS.STREET,HOMEADDRESS.CITY,HOMEADDRESS.POSTAL_CODE)
VALUES (1, 1, 'Beispielstraße 12', 'Köln', '50667');

INSERT INTO PURCHASE (PURCHASE.PURCHASE_ID,PURCHASE.CLIENT_ID)
VALUES(1,1);

INSERT INTO PURCHASEPART(purchase_part_id,purchase_id,thing_id,quantity)
VALUES (1, 1, 1, 1);

COMMIT;

SELECT * FROM CLIENT;
SELECT * FROM HOMEADDRESS;
SELECT * FROM PURCHASE;
SELECT * FROM PURCHASEPART;
SELECT * FROM THING;